api_platform:
    formats:
        json:
            mime_types:
                - application/json
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    eager_loading:
        enabled: true
    defaults:
        pagination:
            pagination_partial: true
            pagination_client_partial: true
            pagination_client_items_per_page: true
            pagination_items_per_page: 10
            pagination_maximum_items_per_page: 20
    collection:
        pagination:
#            enabled: false
            page_parameter_name: _page
#            client_enabled: true
#            enabled_parameter_name: pagination
            items_per_page_parameter_name: itemsPerPage
            partial_parameter_name: 'partial'
    exception_to_status:
        App\Exception\EmptyBodyException: 400
        App\Exception\InvalidConfirmationTokenException: 404